### ISSUE TITLE
Errors during pull

### ISSUE THREAD

**Issue by mbtools** [SAP-samples/abap-cheat-sheets#3]
Hi There,

this looks like a great repo for learning ABAP. It's quite a bit more than a classic cheat sheet :-). 

I tried to pull it into the ABAP docker image which is SAP Basis 7.54 SP 2 and am getting a few errors related to the DDLs:

![image](https://user-images.githubusercontent.com/59966492/206556898-b44af220-7ff6-4d6e-8f35-07f9c6b9892d.png)

For example, the errors refer to this:

https://github.com/SAP-samples/abap-cheat-sheets/blob/514d1cde7db939e51d7c52a5b30649deccc2b346/src/zdemo_abap_rap_draft_m.bdef.asbdef#L2

Is this something you can avoid?

Thanks,
Marc

**Comment by danrega** [comment]
Hi Marc,
thanks for your message.
The issue is, as far as I can see, related to the RAP artifacts in the repo. And since you mentioned 7.54, the CDS view entities are not supported there yer (see, for example, Andrea Schlotthauer's blog [here](https://blogs.sap.com/2022/10/24/feature-matrix-data-modeling-with-abap-core-data-services/)).
And speaking of "strict". The strict mode is used in BDEFs to ensure that the RAP BO is modeled and implemented in accordance with the RAP best practices. That's why it is included here. And this version of the strict mode used in the example (there are newer ones in newer releases) is available as of 7.56. Readme: "The demos cover ABAP syntax irrespective of the ABAP release so as not to scatter information and to have the info in one go. Hence, there may be syntax that is not yet available with the ABAP version of your on-premise system. In that case, you might want to comment out affected code sections if an activation fails." Hence and unfortunately, the RAP examples might not be working. 
Kind regards

**Comment by mbtools** [comment]
Understood. Still, there are ways to make repos work on different releases (and open source examples). Typically this means creating release-specific branches. A bit more work initially but well worth the effort. That way everyone will be able to do clean pulls

**Comment by danrega** [comment]
Hi Marc, 
point taken on this "known issue". That's (different branches) for sure a potential way to go. 
Kind regards
